### ISSUE TITLE
Why transactions doesn't work in this case

### ISSUE THREAD

**Issue by Itisfilipe** [planetscale/database-js#106]
I have this code

```js
async function getDBConnection() {
    const config = {
        host: process.env["DATABASE_HOST"],
        username: process.env["DATABASE_USERNAME"],
        password: process.env["DATABASE_PASSWORD"],
    };
    return connect(config);
}

async function test() {
    const queries = [
        "CREATE TABLE `a` (`id` serial AUTO_INCREMENT PRIMARY KEY NOT NULL)",
        "CREATE TABLE `b` (`id` serial AUTO_INCREMENT PRIMARY KEY NOT NULL)",
        "CREATE TABLE `c` (`id` serial AUTO_INCREMENT PRIMARY KEY NOT NULL)",
        "" // This will fail with DatabaseError: Query was empty
    ]
    const conn = await getDBConnection();
    return conn.transaction(async (tx) => {
        for (const q of queries) {
            await tx.execute(q)
        }
    })
}

test()
    .then((res) => {
        console.log(res);
    })
    .catch((err) => {
        console.log(err);
    });
```

I've executed it and the empty query error was returned

```bash
DatabaseError: Query was empty
    at Connection.execute (.../@planetscale/database/dist/index.js:78:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async .../scripts/run-migration.mjs:115:13
    at async Connection.transaction (.../@planetscale/database/dist/index.js:59:25) {
  status: 400,
  body: { message: 'Query was empty', code: 'UNKNOWN' }
```

I was expecting the tables to not be created but when I go to the console I see

![image](https://user-images.githubusercontent.com/4977614/232542542-66631059-d3af-46fc-bbd6-3d6e380676d9.png)

what I am missing?

**Comment by iheanyi** [comment]
This is because this error that is returned was not actually at the MySQL level but at the API level, a validation error. So since the statement didn't make it to actually execute, it wouldn't rollback the transaction.

**Comment by mattrobenolt** [comment]
Shouldn't we be doing that though? https://github.com/planetscale/database-js/blob/main/src/index.ts#L182-L192

Or does PS not support transactional DDL?

**Comment by mattrobenolt** [comment]
Yeah, I just confirmed, it just simply seems we don't support transactional DDL, so the transaction does nothing in this case. I confirmed this with just a simple `mysql` console, and running `begin; create table ...; rollback` and it's still there.

I'm guessing this is more a limitation of the product, and there isn't anything we can really do differently here.

**Comment by iheanyi** [comment]
> Atomic DDL is not transactional DDL. DDL statements, atomic or otherwise, implicitly end any transaction that is active in the current session, as if you had done a [COMMIT](https://dev.mysql.com/doc/refman/8.0/en/commit.html) before executing the statement. This means that DDL statements cannot be performed within another transaction, within transaction control statements such as [START TRANSACTION ... COMMIT](https://dev.mysql.com/doc/refman/8.0/en/commit.html), or combined with other statements within the same transaction.

@mattrobenolt Good thread to pull on. After some searching, I found that this is actually a limitation of [MySQL](https://dev.mysql.com/doc/refman/8.0/en/atomic-ddl.html). Whenever you run a DDL statement within a transaction, it implicitly ends the transaction. So after the first `CREATE TABLE` statement, it actually sent a `COMMIT` and ended the transaction, so that's why it didn't rollback.

**Comment by mattrobenolt** [comment]
Ah, not even Vitess, MySQL limitation. Yeah, then assuming there's likely nothing we can do here differently since you'd see this same behavior on any driver or mysql client too.

**Comment by Itisfilipe** [comment]
Makes sense, thank you!

**Comment by mscoutermarsh** [comment]
For anyone googling this and curious about making schema migrations with PlanetScale & rolling back in case of errors.

This is built into deploy requests with [gated deployments](https://planetscale.com/docs/concepts/deploy-requests#gated-deployments). The schema will only swap over once all DDL has been successfully staged.
